### ISSUE TITLE
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

### ISSUE THREAD

**Issue by Techbrunch** [sublime-security/sublime-cli#38]
The error appears after the file `setup.cfg` is created (in my case after accepting the privacy warning):

```
cat ~/.config/sublime/setup.cfg
[sublime]
api_key =
save_dir =
permission = True
```

```
sublime version
sublime 0.0.32
  Python 3.12.6
  macOS-15.1-arm64-arm-64bit
```

```
sublime analyze -i redacted.eml -r ~/Github/sublime-rules/detection-rules/

    Messages will be sent to Sublime Security servers in order to run rules and queries.

    This message is intended to preserve your privacy. You only need to accept once.

    Would you like to continue?

 [y/N]: y
Traceback (most recent call last):
  File "/Users/aloha/.local/bin/sublime", line 5, in <module>
    from sublime.cli import main
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/sublime/cli/__init__.py", line 67, in <module>
    main()
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/sublime/cli/decorator.py", line 208, in wrapper
    return function(api_client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/sublime/cli/decorator.py", line 42, in wrapper
    config = load_config()
             ^^^^^^^^^^^^^
  File "/Users/aloha/.local/pipx/venvs/sublime-cli/lib/python3.12/site-packages/sublime/util.py", line 60, in load_config
    config_parser.readfp(config_file)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
```

**Comment by Techbrunch** [comment]
Same issue with:

```
sublime version
sublime 0.0.32
  Python 3.12.6
  macOS-14.7-arm64-arm-64bit
```
